// Generated by Dwene DSIE
export const theme = {
  colors: {
    primary: "#ea580c",
    onPrimary: "#ffffff",
    secondary: "#f97316",
    onSecondary: "#ffffff",
    background: "#0a0a0a",
    surface: "#171717",
    text: "#fafafa",
    muted: "#a3a3a3",
    nav: "#fafafa",
  },
  fonts: {
    display: "\"Space Grotesk\", \"Segoe UI\", sans-serif",
    body: "\"DM Sans\", \"Segoe UI\", sans-serif",
  },
  radius: {
    md: "0.5rem",
  },
  brand: "RicoGram",
} as const;
