// Generated by Dwene DSIE
export const theme = {
  colors: {
    primary: "#be123c",
    onPrimary: "#ffffff",
    secondary: "#be123c",
    onSecondary: "#ffffff",
    background: "#FFFFFF",
    surface: "#ffffff",
    text: "#881337",
    muted: "#64748B",
    nav: "#881337",
  },
  fonts: {
    display: "\"Space Grotesk\", \"Segoe UI\", sans-serif",
    body: "\"DM Sans\", \"Segoe UI\", sans-serif",
  },
  radius: {
    md: "0.75rem",
  },
  brand: "Sneaks",
} as const;
