// Generated by Dwene PCLE + RNIE-lite
import { useEffect } from 'react';
import { HashRouter, Routes, Route, useLocation } from 'react-router-dom';
import { MarketingLayout } from '@/components';
import { Providers } from '@/app/Providers';
import LoginPage from '@/pages/LoginPage';
import RegisterPage from '@/pages/RegisterPage';
import ForgotPasswordPage from '@/pages/ForgotPasswordPage';
import ResetPasswordPage from '@/pages/ResetPasswordPage';
import CheckoutPage from '@/pages/CheckoutPage';
import ProductDetailPage from '@/pages/ProductDetailPage';
import HomePage from '@/pages/HomePage';
import AboutPage from '@/pages/AboutPage';
import ServicesPage from '@/pages/ServicesPage';
import ContactPage from '@/pages/ContactPage';
import ShopPage from '@/pages/ShopPage';

const navItems = [
  {
    "label": "Home",
    "to": "/"
  },
  {
    "label": "Shop",
    "to": "/shop"
  },
  {
    "label": "Services",
    "to": "/services"
  },
  {
    "label": "About",
    "to": "/about"
  },
  {
    "label": "Contact",
    "to": "/contact"
  },
  {
    "label": "Login",
    "to": "/login"
  },
  {
    "label": "Register",
    "to": "/register"
  },
  {
    "label": "Checkout",
    "to": "/checkout"
  }
];

function ScrollToTop() {
  const location = useLocation();
  useEffect(() => {
    try {
      window.scrollTo({ top: 0, left: 0, behavior: 'auto' });
    } catch {
      window.scrollTo(0, 0);
    }
  }, [location.pathname, location.search]);
  return null;
}

export default function App() {
  return (
    <Providers>
      {/* HashRouter: works under /api/ai/sites/<id>/index.html (BrowserRouter stays blank). */}
      <HashRouter>
        <ScrollToTop />
        <Routes>
          <Route element={<MarketingLayout brand={"Sneaks"} navVariant={"floating"} footerVariant={"True"} mobileNavPattern={"drawer"} navItems={navItems} />}>
        <Route index element={<HomePage />} />
        <Route path={"about"} element={<AboutPage />} />
        <Route path={"services"} element={<ServicesPage />} />
        <Route path={"contact"} element={<ContactPage />} />
        <Route path={"shop"} element={<ShopPage />} />
        <Route path="login" element={<LoginPage />} />
        <Route path="register" element={<RegisterPage />} />
        <Route path="forgot-password" element={<ForgotPasswordPage />} />
        <Route path="reset-password" element={<ResetPasswordPage />} />
        <Route path="checkout" element={<CheckoutPage />} />
        <Route path="product/:id" element={<ProductDetailPage />} />
            <Route path="*" element={<HomePage />} />
          </Route>
        </Routes>
      </HashRouter>
    </Providers>
  );
}
