// Generated by Dwene PCLE + RNIE-lite
import { useEffect } from 'react';
import { HashRouter, Routes, Route, useLocation } from 'react-router-dom';
import { MessengerLayout } from '@/components';
import { Providers } from '@/app/Providers';
import LoginPage from '@/pages/LoginPage';
import RegisterPage from '@/pages/RegisterPage';
import ForgotPasswordPage from '@/pages/ForgotPasswordPage';
import ResetPasswordPage from '@/pages/ResetPasswordPage';
import HomePage from '@/pages/HomePage';
import ContactPage from '@/pages/ContactPage';
import FeaturesPage from '@/pages/FeaturesPage';
import SecurityPage from '@/pages/SecurityPage';
import DownloadPage from '@/pages/DownloadPage';
import SupportPage from '@/pages/SupportPage';
import MessagesPage from '@/pages/MessagesPage';
import ProfilePage from '@/pages/ProfilePage';
import FriendsPage from '@/pages/FriendsPage';

const navItems = [
  {
    "label": "Messages",
    "to": "/"
  },
  {
    "label": "Support",
    "to": "/contact"
  }
];

function ScrollToTop() {
  const location = useLocation();
  useEffect(() => {
    try {
      window.scrollTo({ top: 0, left: 0, behavior: 'auto' });
    } catch {
      window.scrollTo(0, 0);
    }
  }, [location.pathname, location.search]);
  return null;
}

export default function App() {
  return (
    <Providers>
      {/* HashRouter: works under /api/ai/sites/<id>/index.html (BrowserRouter stays blank). */}
      <HashRouter>
        <ScrollToTop />
        <Routes>
          <Route element={<MessengerLayout brand={"RicoGram"} chromeVariant={"app-bar"} navItems={navItems} />}>
        <Route index element={<HomePage />} />
        <Route path={"contact"} element={<ContactPage />} />
        <Route path={"features"} element={<FeaturesPage />} />
        <Route path={"security"} element={<SecurityPage />} />
        <Route path={"download"} element={<DownloadPage />} />
        <Route path={"support"} element={<SupportPage />} />
        <Route path={"messages"} element={<MessagesPage />} />
        <Route path={"profile"} element={<ProfilePage />} />
        <Route path={"friends"} element={<FriendsPage />} />
        <Route path="login" element={<LoginPage />} />
        <Route path="register" element={<RegisterPage />} />
        <Route path="forgot-password" element={<ForgotPasswordPage />} />
        <Route path="reset-password" element={<ResetPasswordPage />} />
            <Route path="*" element={<HomePage />} />
          </Route>
        </Routes>
      </HashRouter>
    </Providers>
  );
}
