// Generated by Dwene PCLE — product catalog
export type CatalogProduct = {
  id: string;
  name: string;
  price: number;
  currency?: string;
  description?: string;
  detail?: string;
  images?: string[];
  image?: string;
  sizes?: string[];
  colors?: string[];
  sku?: string;
};

export const CATALOG: CatalogProduct[] = [
  {
    "colors": [
      "Black",
      "White"
    ],
    "currency": "NGN",
    "description": "Signature pick from Sneaks. Replace from Admin anytime.",
    "id": "demo-1",
    "images": [],
    "name": "Sneaks Classic",
    "price": 28,
    "sizes": [
      "S",
      "M",
      "L"
    ],
    "sku": "DEMO-1"
  },
  {
    "colors": [
      "Navy",
      "Cream"
    ],
    "currency": "NGN",
    "description": "Everyday favorite \u2014 edit price, sizes, and photos in Admin.",
    "id": "demo-2",
    "images": [],
    "name": "Sneaks Essentials",
    "price": 42,
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "sku": "DEMO-2"
  },
  {
    "colors": [
      "Forest"
    ],
    "currency": "NGN",
    "description": "Limited drop to show cart + checkout in the preview.",
    "id": "demo-3",
    "images": [],
    "name": "Sneaks Limited",
    "price": 64,
    "sizes": [
      "M",
      "L"
    ],
    "sku": "DEMO-3"
  }
];

export function getProduct(id: string): CatalogProduct | undefined {
  return CATALOG.find((p) => p.id === id);
}

export function productImages(p: CatalogProduct): string[] {
  const imgs = Array.isArray(p.images) ? p.images.filter(Boolean) : [];
  if (imgs.length) return imgs as string[];
  if (p.image) return [p.image];
  return [];
}
